spring:
  datasource:
    url: jdbc:mysql://mysql:3306/unition
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

token:
  secretKey: "dsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idj"
  accessTokenExpirationMillis: 10000000000

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
